
import { AdjectiveEntry } from './types';

export const ADJ_DATA: AdjectiveEntry[] = [
  // N4 Na-Adjectives
  { id: 1, word: "安心な", reading: "あんしんな", meaning: "စိတ်အေးရသော", type: 'na', level: 'N4' },
  { id: 2, word: "安全な", reading: "あんぜんな", meaning: "လုံခြုံစိတ်ချရသော", type: 'na', level: 'N4' },
  { id: 3, word: "大事な", reading: "だいじな", meaning: "အရေးကြီးသော", type: 'na', level: 'N4' },
  { id: 4, word: "不便な", reading: "ふべんな", meaning: "အဆင်မပြေသော", type: 'na', level: 'N4' },
  { id: 5, word: "深い", reading: "ふかい", meaning: "နက်ရှိုင်းသော", type: 'i', level: 'N4' },
  { id: 6, word: "複雑な", reading: "ふくざつな", meaning: "ရှုပ်ထွေးသော", type: 'na', level: 'N4' },
  { id: 7, word: "反対", reading: "はんたい", meaning: "ဆန့်ကျင်သော", type: 'na', level: 'N4' },
  { id: 8, word: "恥ずかしい", reading: "はずかしい", meaning: "ရှက်စရာကောင်းသော", type: 'i', level: 'N4' },
  { id: 9, word: "変な", reading: "へんな", meaning: "ထူးဆန်းသော၊ ပုံမှန်မဟုတ်သော", type: 'na', level: 'N4' },
  { id: 10, word: "ひどい", reading: "ひどい", meaning: "ရက်စက်သော", type: 'i', level: 'N4' },
  { id: 11, word: "久しぶり", reading: "ひさしぶり", meaning: "မတွေ့ရတာကြာသော", type: 'na', level: 'N4' },
  { id: 12, word: "いっぱい", reading: "いっぱい", meaning: "များပြားသော", type: 'na', level: 'N4' },
  { id: 13, word: "一生懸命", reading: "いっしょうけんめい", meaning: "အားသွန်ခွန်စိုက်၊ အစွမ်းကုန်", type: 'na', level: 'N4' },
  { id: 14, word: "自由な", reading: "じゆうな", meaning: "လွတ်လပ်သော", type: 'na', level: 'N4' },
  { id: 15, word: "十分な", reading: "じゅうぶんな", meaning: "လုံလောက်သော", type: 'na', level: 'N4' },
  { id: 16, word: "悲しい", reading: "かなしい", meaning: "ဝမ်းနည်းစရာကောင်းသော", type: 'i', level: 'N4' },
  { id: 17, word: "簡単な", reading: "かんたんな", meaning: "လွယ်ကူသော", type: 'na', level: 'N4' },
  { id: 18, word: "硬い", reading: "かたい", meaning: "မာကျောသော", type: 'i', level: 'N4' },
  { id: 19, word: "厳しい", reading: "きびしい", meaning: "စည်းကမ်းတင်းကျပ်သော", type: 'i', level: 'N4' },
  { id: 20, word: "危険な", reading: "きけんな", meaning: "အန္တရာယ်များသော", type: 'na', level: 'N4' },
  { id: 21, word: "細かい", reading: "こまかい", meaning: "အသေးစိတ်ကျသော", type: 'i', level: 'N4' },
  { id: 22, word: "怖い", reading: "こわい", meaning: "ကြောက်စရာကောင်းသော", type: 'i', level: 'N4' },
  { id: 23, word: "珍しい", reading: "めずらしい", meaning: "ရှားပါးသော", type: 'i', level: 'N4' },
  { id: 24, word: "無理な", reading: "むりな", meaning: "မဖြစ်နိုင်သော", type: 'na', level: 'N4' },
  { id: 25, "word": "眠い", "reading": "ねむい", "meaning": "အိပ်ငိုက်သော", "type": "i", "level": "N4" },
  { id: 26, "word": "苦い", "reading": "にがい", "meaning": "ခါးသော", "type": "i", "level": "N4" },
  { id: 27, "word": "おかしい", "reading": "おかしい", "meaning": "ထူးဆန်းသော/ပုံမှန်မဟုတ်သော", "type": "i", "level": "N4" },
  { id: 28, "word": "さびしい", "reading": "さびしい", "meaning": "အထီးကျန်သော", "type": "i", "level": "N4" },
  { id: 29, "word": "親切な", "reading": "しんせつな", "meaning": "ကြင်နာတတ်သော", "type": "na", "level": "N4" },
  { id: 30, "word": "素晴らしい", "reading": "すばらしい", "meaning": "ထူးချွန်ပြောင်မြောက်သော", "type": "i", "level": "N4" },
  { id: 31, "word": "凄い", "reading": "すごい", "meaning": "အရမ်း (တော်သော၊ ကောင်းသော)", "type": "i", "level": "N4" },
  { id: 32, "word": "正しい", "reading": "ただしい", "meaning": "မှန်ကန်သော", "type": "i", "level": "N4" },
  { id: 33, "word": "丁寧な", "reading": "ていねいな", "meaning": "ယဉ်ကျေးသော၊ စိတ်ရှည်သော", "type": "na", "level": "N4" },
  { id: 34, "word": "適当な", "reading": "てきとうな", "meaning": "သင့်တော်သော", "type": "na", "level": "N4" },
  { id: 35, "word": "特別な", "reading": "とくべつな", "meaning": "အထူးတလည်ဖြစ်သော", "type": "na", "level": "N4" },
  { id: 36, "word": "嬉しい", "reading": "うれしい", "meaning": "ပျော်ရွှင်သော", "type": "i", "level": "N4" },
  { id: 37, "word": "美しい", "reading": "うつくしい", "meaning": "လှပသော", "type": "i", "level": "N4" },
  { id: 38, "word": "優しい", "reading": "やさしい", "meaning": "သဘောကောင်းသော", "type": "i", "level": "N4" },
  { id: 39, "word": "柔らかい", "reading": "やわらかい", "meaning": "ပျော့ပြောင်းသော", "type": "i", "level": "N4" },
  { id: 40, "word": "残念な", "reading": "ざんねんな", "meaning": "ဝမ်းနည်းသော", "type": "na", "level": "N4" },
  // N4 I-Adjectives
  { id: 41, "word": "浅い", "reading": "あさい", "meaning": "ပေါ့သော", "type": "i", "level": "N4" },
  { id: 42, "word": "固い", "reading": "かたい", "meaning": "မာသော", "type": "i", "level": "N4" },
  { id: 43, "word": "堅い", "reading": "かたい", "meaning": "တင်းကျပ်သော၊ သေချာသော", "type": "i", "level": "N4" },
  { id: 44, "word": "うまい", "reading": "うまい", "meaning": "ကျွမ်းကျင်သော၊ အရသာရှိသော", "type": "i", "level": "N4" },
  { id: 45, "word": "羨ましい", "reading": "うらやましい", "meaning": "အားကျသော", "type": "i", "level": "N4" },
  { id: 46, "word": "偉い", "reading": "えらい", "meaning": "လွဲသော", "type": "i", "level": "N4" },
  { id: 47, "word": "恐ろしい", "reading": "おそろしい", "meaning": "စိုးရိမ်ပူပန်သော", "type": "i", "level": "N4" },
  { id: 48, "word": "大人しい", "reading": "おとなしい", "meaning": "တိတ်ဆိတ်သော၊ လူကြီးဆန်သော", "type": "i", "level": "N4" },
  { id: 49, "word": "重たい", "reading": "おもたい", "meaning": "လေးလံသော", "type": "i", "level": "N4" },
  { id: 50, "word": "硬い", "reading": "かたい", "meaning": "တင်းမာသော", "type": "i", "level": "N4" },
  { id: 51, "word": "きつい", "reading": "きつい", "meaning": "တင်းကြပ်သော", "type": "i", "level": "N4" },
  { id: 52, "word": "臭い", "reading": "くさい", "meaning": "ပုပ်သိုးသော", "type": "i", "level": "N4" },
  { id: 53, "word": "詳しい", "reading": "くわしい", "meaning": "အသေးစိတ်ဖြစ်သော", "type": "i", "level": "N4" },
  { id: 54, "word": "煙い", "reading": "けむい", "meaning": "မီးခိုးမွှန်သော", "type": "i", "level": "N4" },
  { id: 55, "word": "塩辛い", "reading": "しおからい", "meaning": "ငန်သော", "type": "i", "level": "N4" },
  { id: 56, "word": "四角い", "reading": "しかくい", "meaning": "လေးထောင့်ကျသော", "type": "i", "level": "N4" },
  { id: 57, "word": "仕方ない", "reading": "しかたない", "meaning": "နည်းလမ်းမရှိသော", "type": "i", "level": "N4" },
  { id: 58, "word": "しょうがない", "reading": "しょうがない", "meaning": "မတတ်နိုင်သော", "type": "i", "level": "N4" },
  { id: 59, "word": "だるい", "reading": "だるい", "meaning": "ညောင်းညာလေးလံသော", "type": "i", "level": "N4" },
  { id: 60, "word": "つらい", "reading": "つらい", "meaning": "ခါးသီးသော (အမှန်တရား)", "type": "i", "level": "N4" },
  { id: 61, "word": "懐かしい", "reading": "なつかしい", "meaning": "လွမ်းဆွတ်သတိရသော", "type": "i", "level": "N4" },
  { id: 62, "word": "幅広い", "reading": "はばひろい", "meaning": "နယ်ပယ်ကျယ်ပြန့်သော", "type": "i", "level": "N4" },
  { id: 63, "word": "もったいない", "reading": "もったいない", "meaning": "နှမြောစရာကောင်းသော", "type": "i", "level": "N4" },
  { id: 64, "word": "宜しい", "reading": "よろしい", "meaning": "သင့်တော်ကောင်းမွန်သော", "type": "i", "level": "N4" },
  { id: 65, "word": "詰まらない", "reading": "つまらない", "meaning": "ပျင်းစရာကောင်းသော", "type": "i", "level": "N4" },
  // N5 I-Adjectives
  { id: 101, "word": "青い", "reading": "あおい", "meaning": "ပြာသော", "type": "i", "level": "N5" },
  { id: 102, "word": "大きい", "reading": "おおきい", "meaning": "ကြီးသော", "type": "i", "level": "N5" },
  { id: 103, "word": "少ない", "reading": "すくない", "meaning": "နည်းသော", "type": "i", "level": "N5" },
  { id: 104, "word": "低い", "reading": "ひくい", "meaning": "ပုသော၊ နိမ့်သော", "type": "i", "level": "N5" },
  { id: 105, "word": "赤い", "reading": "あかい", "meaning": "နီသော", "type": "i", "level": "N5" },
  { id: 106, "word": "すごい", "reading": "すごい", "meaning": "တော်သော၊ မိုက်သော", "type": "i", "level": "N5" },
  { id: 107, "word": "広い", "reading": "ひろい", "meaning": "ကျယ်သော", "type": "i", "level": "N5" },
  { id: 108, "word": "明るい", "reading": "あかるい", "meaning": "လင်းသော", "type": "i", "level": "N5" },
  { id: 109, "word": "遅い", "reading": "おそい", "meaning": "နောက်ကျသော", "type": "i", "level": "N5" },
  { id: 110, "word": "涼しい", "reading": "すずしい", "meaning": "အေးမြသော", "type": "i", "level": "N5" },
  { id: 111, "word": "太い", "reading": "ふとい", "meaning": "ဝသော", "type": "i", "level": "N5" },
  { id: 112, "word": "暖かい", "reading": "あたたかい", "meaning": "နွေးထွေးသော", "type": "i", "level": "N5" },
  { id: 113, "word": "温かい", "reading": "あたたかい", "meaning": "နွေးသော", "type": "i", "level": "N5" },
  { id: 114, "word": "重い", "reading": "おもい", "meaning": "လေးသော", "type": "i", "level": "N5" },
  { id: 115, "word": "酸っぱい", "reading": "すっぱい", "meaning": "ချဉ်သော", "type": "i", "level": "N5" },
  { id: 116, "word": "古い", "reading": "ふるい", "meaning": "ဟောင်းသော", "type": "i", "level": "N5" },
  { id: 117, "word": "新しい", "reading": "あたらしい", "meaning": "သစ်လွင်သော", "type": "i", "level": "N5" },
  { id: 118, "word": "面白い", "reading": "おもしろい", "meaning": "စိတ်ဝင်စားဖွယ်ကောင်းသော", "type": "i", "level": "N5" },
  { id: 119, "word": "欲しい", "reading": "ほしい", "meaning": "လိုချင်သော", "type": "i", "level": "N5" },
  { id: 120, "word": "熱い", "reading": "あつい", "meaning": "ပူသော", "type": "i", "level": "N5" },
  { id: 121, "word": "辛い", "reading": "からい", "meaning": "စပ်သော", "type": "i", "level": "N5" },
  { id: 122, "word": "白い", "reading": "しろい", "meaning": "ဖြူသော", "type": "i", "level": "N5" },
  { id: 123, "word": "狭い", "reading": "せまい", "meaning": "ကျဉ်းသော", "type": "i", "level": "N5" },
  { id: 124, "word": "細い", "reading": "ほそい", "meaning": "ပိန်သော", "type": "i", "level": "N5" },
  { id: 125, "word": "軽い", "reading": "かるい", "meaning": "ပေါ့သော", "type": "i", "level": "N5" },
  { id: 126, "word": "高い", "reading": "たかい", "meaning": "မြင့်သော၊ ဈေးကြီးသော", "type": "i", "level": "N5" },
  { id: 127, "word": "まずい", "reading": "まずい", "meaning": "အရသာမရှိသော", "type": "i", "level": "N5" },
  { id: 128, "word": "厚い", "reading": "あつい", "meaning": "ထူသော", "type": "i", "level": "N5" },
  { id: 129, "word": "可愛い", "reading": "かわいい", "meaning": "ချစ်စရာကောင်းသော", "type": "i", "level": "N5" },
  { id: 130, "word": "楽しい", "reading": "たのしい", "meaning": "ပျော်သော", "type": "i", "level": "N5" },
  { id: 131, "word": "丸い", "reading": "まるい", "meaning": "လုံးသော", "type": "i", "level": "N5" },
  { id: 132, "word": "危ない", "reading": "あぶない", "meaning": "အန္တရာယ်များသော", "type": "i", "level": "N5" },
  { id: 133, "word": "黄色い", "reading": "きいろい", "meaning": "ဝါသော", "type": "i", "level": "N5" },
  { id: 134, "word": "小さい", "reading": "ちいさい", "meaning": "သေးငယ်သော", "type": "i", "level": "N5" },
  { id: 135, "word": "短い", "reading": "みじかい", "meaning": "တိုသော", "type": "i", "level": "N5" },
  { id: 136, "word": "甘い", "reading": "あまい", "meaning": "ချိုသော", "type": "i", "level": "N5" },
  { id: 137, "word": "汚い", "reading": "きたない", "meaning": "ညစ်ပေသော", "type": "i", "level": "N5" },
  { id: 138, "word": "強い", "reading": "つよい", "meaning": "အားကောင်းသော", "type": "i", "level": "N5" },
  { id: 139, "word": "蒸し暑い", "reading": "むしあつい", "meaning": "ပူအိုက်သော", "type": "i", "level": "N5" },
  { id: 140, "word": "良い", "reading": "よい", "meaning": "ကောင်းသော", "type": "i", "level": "N5" },
  { id: 141, "word": "暗い", "reading": "くらい", "meaning": "မှောင်သော", "type": "i", "level": "N5" },
  { id: 142, "word": "遠い", "reading": "とおい", "meaning": "ဝေးသော", "type": "i", "level": "N5" },
  { id: 143, "word": "難しい", "reading": "むずかしい", "meaning": "ခက်ခဲသော", "type": "i", "level": "N5" },
  { id: 144, "word": "忙しい", "reading": "いそがしい", "meaning": "အလုပ်များသော", "type": "i", "level": "N5" },
  { id: 145, "word": "速い", "reading": "はやい", "meaning": "မြန်သော", "type": "i", "level": "N5" },
  { id: 146, "word": "黒い", "reading": "くろい", "meaning": "မည်းသော", "type": "i", "level": "N5" },
  { id: 147, "word": "無い", "reading": "ない", "meaning": "ဘာမှမရှိသော", "type": "i", "level": "N5" },
  { id: 148, "word": "易しい", "reading": "やさしい", "meaning": "လွယ်ကူသော", "type": "i", "level": "N5" },
  { id: 149, "word": "痛い", "reading": "いたい", "meaning": "နာကျင်သော", "type": "i", "level": "N5" },
  { id: 150, "word": "濃い", "reading": "こい", "meaning": "ရင့်သော (ဖြစ်သော)", "type": "i", "level": "N5" },
  { id: 151, "word": "長い", "reading": "ながい", "meaning": "ရှည်လျားသော", "type": "i", "level": "N5" },
  { id: 152, "word": "安い", "reading": "やすい", "meaning": "ဈေးပေါသော", "type": "i", "level": "N5" },
  { id: 153, "word": "薄い", "reading": "うすい", "meaning": "ပါးသော", "type": "i", "level": "N5" },
  { id: 154, "word": "怖い", "reading": "こわい", "meaning": "ကြောက်သော", "type": "i", "level": "N5" },
  { id: 155, "word": "苦い", "reading": "にがい", "meaning": "ခါးသော", "type": "i", "level": "N5" },
  { id: 156, "word": "弱い", "reading": "よわい", "meaning": "အားနည်းသော", "type": "i", "level": "N5" },
  { id: 157, "word": "うるさい", "reading": "うるさい", "meaning": "ဆူညံသော", "type": "i", "level": "N5" },
  { id: 158, "word": "寒い", "reading": "さむい", "meaning": "ချမ်းသော", "type": "i", "level": "N5" },
  { id: 159, "word": "若い", "reading": "わかい", "meaning": "ငယ်ရွယ်သော", "type": "i", "level": "N5" },
  { id: 160, "word": "早い", "reading": "はやい", "meaning": "စောသော", "type": "i", "level": "N5" },
  { id: 161, "word": "悪い", "reading": "わるい", "meaning": "မကောင်းသော", "type": "i", "level": "N5" },
  { id: 162, "word": "多い", "reading": "おおい", "meaning": "များသော", "type": "i", "level": "N5" },
  { id: 163, "word": "冷たい", "reading": "つめたい", "meaning": "အေးမြသော", "type": "i", "level": "N5" },
  { id: 164, "word": "美味しい", "reading": "おいしい", "meaning": "အရသာရှိသော", "type": "i", "level": "N5" },
  { id: 165, "word": "近い", "reading": "ちかい", "meaning": "နီးသော", "type": "i", "level": "N5" }
];
