
import { VocabularyEntry } from './types';

export const N5_DATA: VocabularyEntry[] = [
  { id: 1, kanji: "山", reading: "やま", meaning: "တောင်" },
  { id: 2, kanji: "ふじ山", reading: "ふじさん", meaning: "ဖူဂျီတောင်" },
  { id: 3, kanji: "川", reading: "かわ", meaning: "မြစ်" },
  { id: 4, kanji: "インダス川", reading: "インダスがわ", meaning: "Indus မြစ်" },
  { id: 5, kanji: "水田", reading: "すいでん", meaning: "စပါးခင်း" },
  { id: 6, kanji: "油田", reading: "ゆでん", meaning: "ရေနံမြေ" },
  { id: 7, kanji: "日", reading: "ひ", meaning: "နေ့" },
  { id: 8, kanji: "日本", reading: "にほん", meaning: "ဂျပန်" },
  { id: 9, kanji: "月", reading: "つき", meaning: "လ" },
  { id: 10, kanji: "一月", reading: "いちがつ", meaning: "ဇန်နဝါရီလ" },
  { id: 11, kanji: "今月", reading: "こんげつ", meaning: "ဒီလ" },
  { id: 12, kanji: "火", reading: "ひ", meaning: "မီး" },
  { id: 13, kanji: "火山", reading: "かざん", meaning: "မီးတောင်" },
  { id: 14, kanji: "火事", reading: "かじ", meaning: "မီးလောင်မှု" },
  { id: 15, kanji: "水", reading: "みず", meaning: "ရေ" },
  { id: 16, kanji: "木", reading: "き", meaning: "သစ်ပင်" },
  { id: 17, kanji: "お金", reading: "おかね", meaning: "ပိုက်ဆံ" },
  { id: 18, kanji: "土地", reading: "とち", meaning: "မြေ၊ မြေကြီး" },
  { id: 19, kanji: "十分な", reading: "じゅうぶんな", meaning: "လုံလောက်သော" },
  { id: 20, kanji: "上", reading: "うえ", meaning: "အပေါ်" },
  { id: 21, kanji: "上がる", reading: "あがる", meaning: "မြင့်တက်သည်" },
  { id: 22, kanji: "水上", reading: "すいじょう", meaning: "ရေပေါ်" },
  { id: 23, kanji: "上着", reading: "うわぎ", meaning: "အပေါ်ဝတ်အင်္ကျီ" },
  { id: 24, kanji: "下がる", reading: "さがる", meaning: "လျော့ကျသည်" },
  { id: 25, kanji: "下着", reading: "したぎ", meaning: "အတွင်းခံ" },
  { id: 26, kanji: "上下", reading: "じょうげ", meaning: "အပေါ်အောက်" },
  { id: 27, kanji: "中", reading: "なか", meaning: "အထဲ၊ အတွင်း" },
  { id: 28, kanji: "一日中", reading: "いちにちじゅう", meaning: "တစ်နေ့လုံး" },
  { id: 29, kanji: "中学", reading: "ちゅうがく", meaning: "အလယ်တန်း" },
  { id: 30, kanji: "半年", reading: "はんとし", meaning: "နှစ်ဝက်" },
  { id: 31, kanji: "半分", reading: "はんぶん", meaning: "တစ်ဝက်" },
  { id: 32, kanji: "分かる", reading: "わかる", meaning: "နားလည်သည်" },
  { id: 33, kanji: "分ける", reading: "わける", meaning: "ခွဲသည်" },
  { id: 34, kanji: "一人", reading: "ひとり", meaning: "တစ်ယောက်" },
  { id: 35, kanji: "二人", reading: "ふたり", meaning: "နှစ်ယောက်" },
  { id: 36, kanji: "日本人", reading: "にほんじん", meaning: "ဂျပန်လူမျိုး" },
  { id: 37, kanji: "子ども", reading: "こども", meaning: "ကလေး" },
  { id: 38, kanji: "親子", reading: "おやこ", meaning: "မိဘနှင့်ကလေး" },
  { id: 39, kanji: "女子", reading: "じょし", meaning: "မိန်းကလေး" },
  { id: 40, kanji: "女の子", reading: "おんなのこ", meaning: "မိန်းကလေး" },
  { id: 41, kanji: "男", reading: "おとこ", meaning: "ယောက်ျားလေး" },
  { id: 42, kanji: "男女", reading: "だんじょ", meaning: "ကျားမ" },
  { id: 43, kanji: "男の子", reading: "おとこのこ", meaning: "ယောက်ျားလေး" },
  { id: 44, kanji: "長男", reading: "ちょうなん", meaning: "သားကြီး" },
  { id: 45, kanji: "長女", reading: "ちょうじょ", meaning: "သမီးကြီး" },
  { id: 46, kanji: "目", reading: "め", meaning: "မျက်လုံး" },
  { id: 47, kanji: "一日目", reading: "いちにちめ", meaning: "တစ်ရက်မြောက်နေ့" },
  { id: 48, kanji: "口", reading: "くち", meaning: "ပါးစပ်" },
  { id: 49, kanji: "入口", reading: "いりぐち", meaning: "ဝင်ပေါက်" },
  { id: 50, kanji: "出口", reading: "でぐち", meaning: "ထွက်ပေါက်" },
  { id: 51, kanji: "人口", reading: "じんこう", meaning: "လူဦးရေ" },
  { id: 52, kanji: "耳", reading: "みみ", meaning: "နားရွက်" },
  { id: 53, kanji: "手", reading: "て", meaning: "လက်" },
  { id: 54, kanji: "上手な", reading: "じょうずな", meaning: "တော်သော၊ ကျွမ်းကျင်သော" },
  { id: 55, kanji: "下手な", reading: "へたな", meaning: "ညံ့သော၊ ဖျင်းသော" },
  { id: 56, kanji: "足", reading: "あし", meaning: "ခြေထောက်" },
  { id: 57, kanji: "足りる", reading: "たりる", meaning: "လုံလောက်သည်" },
  { id: 58, kanji: "一足", reading: "いっそく", meaning: "(ခြေ)တစ်လှမ်း" },
  { id: 59, kanji: "力", reading: "ちから", meaning: "အား၊ အင်အား" },
  { id: 60, kanji: "水力", reading: "すいりょく", meaning: "ရေအား" },
  { id: 61, kanji: "体力", reading: "たいりょく", meaning: "ကိုယ်ကာယအား" },
  { id: 62, kanji: "お父さん", reading: "おとうさん", meaning: "အဖေ" },
  { id: 63, kanji: "父親", reading: "ちちおや", meaning: "ဖခင်" },
  { id: 64, kanji: "お母さん", reading: "おかあさん", meaning: "အမေ" },
  { id: 65, kanji: "母親", reading: "ははおや", meaning: "မိခင်" },
  { id: 66, kanji: "父母", reading: "ふぼ", meaning: "မိဘ" },
  { id: 67, kanji: "母国", reading: "ぼこく", meaning: "မိခင်နိုင်ငံ" },
  { id: 68, kanji: "先", reading: "さき", meaning: "စောစောက၊ အရင်" },
  { id: 69, kanji: "先月", reading: "せんげつ", meaning: "ပြီးခဲ့တဲ့လ" },
  { id: 70, kanji: "生まれる", reading: "うまれる", meaning: "မွေးဖွားသည်" },
  { id: 71, kanji: "生む", reading: "うむ", meaning: "မွေးဖွားသည်" },
  { id: 72, kanji: "先生", reading: "せんせい", meaning: "ဆရာ၊ ဆရာမ" },
  { id: 73, kanji: "生きる", reading: "いきる", meaning: "အသက်ရှင်သည်" },
  { id: 74, kanji: "生活", reading: "せいかつ", meaning: "နေထိုင်မှုဘဝ" },
  { id: 75, kanji: "学ぶ", reading: "まなぶ", meaning: "သင်ယူသည်" },
  { id: 76, "kanji": "学生", "reading": "がくせい", "meaning": "ကျောင်းသားကျောင်းသူ" },
  { id: 77, "kanji": "大学", "reading": "だいがく", "meaning": "တက္ကသိုလ်" },
  { id: 78, "kanji": "学校", "reading": "がっこう", "meaning": "ကျောင်း" },
  { id: 79, "kanji": "校長", "reading": "こうちょう", "meaning": "ကျောင်းအုပ်" },
  { id: 80, "kanji": "友人", "reading": "ゆうじん", "meaning": "မိတ်ဆွေ" },
  { id: 81, "kanji": "友達", "reading": "ともだち", "meaning": "သူငယ်ချင်း" },
  { id: 82, "kanji": "本", "reading": "ほん", "meaning": "စာအုပ်" },
  { id: 83, "kanji": "毎月", "reading": "まいつき", "meaning": "လစဉ်၊ လတိုင်း" },
  { id: 84, "kanji": "毎日", "reading": "まいにち", "meaning": "နေ့စဉ်၊ နေ့တိုင်း" },
  { id: 85, "kanji": "毎年", "reading": "まいとし", "meaning": "နှစ်စဉ်၊ နှစ်တိုင်း" },
  { id: 86, "kanji": "毎朝", "reading": "まいあさ", "meaning": "မနက်တိုင်း" },
  { id: 87, "kanji": "何", "reading": "なに", "meaning": "ဘာ" },
  { id: 88, "kanji": "何月", "reading": "なんがつ", "meaning": "ဘယ်လ" },
  { id: 89, "kanji": "何人", "reading": "なんにん", "meaning": "ဘယ်နှယောက်" },
  { id: 90, "kanji": "何時", "reading": "なんじ", "meaning": "ဘယ်နှနာရီ" },
  { id: 91, "kanji": "前", "reading": "まえ", "meaning": "ရှေ့" },
  { id: 92, "kanji": "後", "reading": "あと", "meaning": "နောက်" },
  { id: 93, "kanji": "前半", "reading": "ぜんはん", "meaning": "ရှေ့ပိုင်း" },
  { id: 94, "kanji": "午前", "reading": "ごぜん", "meaning": "မနက်ပိုင်း (AM)" },
  { id: 95, "kanji": "午後", "reading": "ごご", "meaning": "မွန်းလွဲပိုင်း (PM)" },
  { id: 96, "kanji": "前後", "reading": "ぜんご", "meaning": "ရှေ့နောက်" },
  { id: 97, "kanji": "後ろ", "reading": "うしろ", "meaning": "အနောက်" },
  { id: 98, "kanji": "外", "reading": "そと", "meaning": "အပြင်" },
  { id: 99, "kanji": "外国", "reading": "がいこく", "meaning": "နိုင်ငံခြား၊ ပြည်ပ" },
  { id: 100, "kanji": "左", "reading": "ひだり", "meaning": "ဘယ်ဘက်၊ လက်ဝဲဘက်" },
  { id: 101, "kanji": "右", "reading": "みぎ", "meaning": "ညာဘက်၊ လက်ယာဘက်" },
  { id: 102, "kanji": "左右", "reading": "さゆう", "meaning": "ဘယ်ညာ" },
  { id: 103, "kanji": "石", "reading": "いし", "meaning": "ကျောက်တုံး" },
  { id: 104, "kanji": "東", "reading": "ひがし", "meaning": "အရှေ့အရပ်" },
  { id: 105, "kanji": "東口", "reading": "ひがしぐち", "meaning": "အရှေ့ပေါက်" },
  { id: 106, "kanji": "東京", "reading": "とうきょう", "meaning": "တိုကျို" },
  { id: 107, "kanji": "西", "reading": "にし", "meaning": "အနောက်အရပ်" },
  { id: 108, "kanji": "南", "reading": "みなみ", "meaning": "တောင်အရပ်" },
  { id: 109, "kanji": "北", "reading": "きた", "meaning": "မြောက်အရပ်" },
  { id: 110, "kanji": "東南", "reading": "とうなん", "meaning": "အရှေ့တောင်" },
  { id: 111, "kanji": "名前", "reading": "なまえ", "meaning": "နာမည်" },
  { id: 112, "kanji": "有名な", "reading": "ゆうめな", "meaning": "ကျော်ကြားသော၊ နာမည်ကြီးသော" },
  { id: 113, "kanji": "牛", "reading": "うし", "meaning": "နွား" },
  { id: 114, "kanji": "水牛", "reading": "すいぎゅう", "meaning": "ကျွဲ" },
  { id: 115, "kanji": "牛乳", "reading": "ぎゅうにゅう", "meaning": "နွားနို့" },
  { id: 116, "kanji": "牛肉", "reading": "ぎゅうにく", "meaning": "おမဲသား" },
  { id: 117, "kanji": "馬", "reading": "うま", "meaning": "မြင်း" },
  { id: 118, "kanji": "馬車", "reading": "ばしゃ", "meaning": "မြင်းလှည်း" },
  { id: 119, "kanji": "魚", "reading": "さかな", "meaning": "ငါး" },
  { id: 120, "kanji": "人魚", "reading": "にんぎょ", "meaning": "ရေသူမ" },
  { id: 121, "kanji": "金魚", "reading": "きんぎょ", "meaning": "ရွှေငါး" },
  { id: 122, "kanji": "貝がら", "reading": "かいがら", "meaning": "ခရုခွံ" },
  { id: 123, "kanji": "雨", "reading": "あめ", "meaning": "မိုး" },
  { id: 124, "kanji": "大雨", "reading": "おおあめ", "meaning": "မိုးကြီးခြင်း" },
  { id: 125, "kanji": "天気", "reading": "てんき", "meaning": "မိုးလေဝသ" },
  { id: 126, "kanji": "空気", "reading": "くうき", "meaning": "လေ၊ လေထု" },
  { id: 127, "kanji": "人気がある", "reading": "にんきがある", "meaning": "လူကြိုက်များသည်" },
  { id: 128, "kanji": "気持ち", "reading": "きもち", "meaning": "စိတ်" },
  { id: 129, "kanji": "車", "reading": "くるま", "meaning": "ကား" },
  { id: 130, "kanji": "電車", "reading": "でんしゃ", "meaning": "ရထား" },
  { id: 131, "kanji": "門", "reading": "もん", "meaning": "ဂိတ်ပေါက်" },
  { id: 132, "kanji": "大きい", "reading": "おおきい", "meaning": "ကြီးသော" },
  { id: 133, "kanji": "小さい", "reading": "ちいさい", "meaning": "သေးသော" },
  { id: 134, "kanji": "小川", "reading": "おがわ", "meaning": "စမ်းချောင်း" },
  { id: 135, "kanji": "小学校", "reading": "しょうがっこう", "meaning": "မူလတန်းကျောင်း" },
  { id: 136, "kanji": "犬", "reading": "いぬ", "meaning": "ခွေး" },
  { id: 137, "kanji": "子犬", "reading": "こいぬ", "meaning": "ခွေးပေါက်" },
  { id: 138, "kanji": "高い", "reading": "たかい", "meaning": "ဈေးကြီးသော၊ မြင့်သော" },
  { id: 139, "kanji": "高校生", "reading": "こうこうせい", "meaning": "အထက်တန်းကျောင်းသား" },
  { id: 140, "kanji": "安い", "reading": "やすい", "meaning": "ဈေးချိုသော" },
  { id: 141, "kanji": "安心な", "reading": "あんしんな", "meaning": "စိတ်အေးသော" },
  { id: 142, "kanji": "安全な", "reading": "あんぜんな", "meaning": "လုံခြုံစိတ်ချရသော၊ ဘေးကင်းသော" },
  { id: 143, "kanji": "新しい", "reading": "あたらしい", "meaning": "သစ်သော" },
  { id: 144, "kanji": "新聞", "reading": "しんぶん", "meaning": "သတင်းစာ" },
  { id: 145, "kanji": "新人", "reading": "しんじん", "meaning": "လူသစ်" },
  { id: 146, "kanji": "新年", "reading": "しんねん", "meaning": "နှစ်သစ်" },
  { id: 147, "kanji": "古い", "reading": "ふるい", "meaning": "ဟောင်းသော" },
  { id: 148, "kanji": "中古車", "reading": "ちゅうこしゃ", "meaning": "တစ်ပတ်ရစ်" },
  { id: 149, "kanji": "長い", "reading": "ながい", "meaning": "ရှည်သော" },
  { id: 150, "kanji": "学長", "reading": "がくちょう", "meaning": "ကျောင်းအုပ်" },
  { id: 151, "kanji": "多い", "reading": "おおい", "meaning": "များသော" },
  { id: 152, "kanji": "多少", "reading": "たしょう", "meaning": "အနည်းငယ်" },
  { id: 153, "kanji": "少ない", "reading": "すくない", "meaning": "နည်းသော" },
  { id: 154, "kanji": "少し", "reading": "すこし", "meaning": "အနည်းငယ်" },
  { id: 155, "kanji": "早い", "reading": "はやい", "meaning": "မြန်သော" },
  { id: 156, "kanji": "早朝", "reading": "そうちょう", "meaning": "စောစော" },
  { id: 157, "kanji": "社長", "reading": "しゃちょう", "meaning": "သူဌေး၊ ကုမ္ပဏီဥက္ကဋ္ဌ" },
  { id: 158, "kanji": "行く", "reading": "いく", "meaning": "သွားသည်" },
  { id: 159, "kanji": "行う", "reading": "おこなう", "meaning": "ကျင်းပသည်" },
  { id: 160, "kanji": "行き方", "reading": "いきかた", "meaning": "သွားပုံသွားနည်း" },
  { id: 161, "kanji": "銀行", "reading": "ぎんこう", "meaning": "ဘဏ်" },
  { id: 162, "kanji": "行目", "reading": "ぎょうめ", "meaning": "အကြောင်းမြောက် (မျဉ်းကြောင်း)" },
  { id: 163, "kanji": "来ます", "reading": "きます", "meaning": "လာသည်" },
  { id: 164, "kanji": "来年", "reading": "らいねん", "meaning": "နောက်နှစ်၊ လာမယ့်နှစ်" },
  { id: 165, "kanji": "来週", "reading": "らいしゅう", "meaning": "နောက်တစ်ပတ်၊ လာမယ့်အပတ်" },
  { id: 166, "kanji": "将来", "reading": "しょうらい", "meaning": "အနာဂတ်" },
  { id: 167, "kanji": "食べる", "reading": "たべる", "meaning": "စားသည်" },
  { id: 168, "kanji": "外食する", "reading": "がいしょくする", "meaning": "အပြင်ထွက်စားသည်" },
  { id: 169, "kanji": "食堂", "reading": "しょくどう", "meaning": "ထမင်းစားခန်း" },
  { id: 170, "kanji": "見る", "reading": "みる", "meaning": "ကြည့်သည်" },
  { id: 171, "kanji": "見せる", "reading": "みせる", "meaning": "ပြသည်" },
  { id: 172, "kanji": "見学する", "reading": "けんがくする", "meaning": "ကြည့်ရှုလေ့လာသည်" },
  { id: 173, "kanji": "意見", "reading": "いけん", "meaning": "ထင်မြင်ချက်" },
  { id: 174, "kanji": "入る", "reading": "はいる", "meaning": "ဝင်သည်" },
  { id: 175, "kanji": "入れる", "reading": "いれる", "meaning": "ထည့်သည်" },
  { id: 176, "kanji": "入学する", "reading": "にゅうがくする", "meaning": "ကျောင်းတက်သည်" },
  { id: 177, "kanji": "出る", "reading": "でる", "meaning": "ထွက်သည်" },
  { id: 178, "kanji": "出す", "reading": "だす", "meaning": "ထုတ်သည်" },
  { id: 179, "kanji": "出席する", "reading": "しゅっせきする", "meaning": "တက်ရောက်သည်" },
  { id: 180, "kanji": "立つ", "reading": "たつ", "meaning": "မတ်တပ်ရပ်သည်" },
  { id: 181, "kanji": "国立大学", "reading": "こくりつだいがく", "meaning": "နိုင်ငံပိုင်တက္ကသိုလ်" },
  { id: 182, "kanji": "書く", "reading": "かく", "meaning": "ရေးသည်" },
  { id: 183, "kanji": "辞書", "reading": "じしょ", "meaning": "အဘိဓာန်" },
  { id: 184, "kanji": "下書き", "reading": "したがき", "meaning": "အကြမ်းရေးခြင်း" },
  { id: 185, "kanji": "読書", "reading": "どくしょ", "meaning": "စာဖတ်ခြင်း" },
  { id: 186, "kanji": "言う", "reading": "いう", "meaning": "ပြောသည်" },
  { id: 187, "kanji": "言語", "reading": "げんご", "meaning": "ဘာသာစကား" },
  { id: 188, "kanji": "伝言", "reading": "でんごん", "meaning": "တဆင့်စကား" },
  { id: 189, "kanji": "飲む", "reading": "のむ", "meaning": "သောက်သည်" },
  { id: 190, "kanji": "飲み物", "reading": "のみもの", "meaning": "သောက်စရာ" },
  { id: 191, "kanji": "飲食", "reading": "いんしょく", "meaning": "အစားအသောက်" },
  { id: 192, "kanji": "話す", "reading": "はなす", "meaning": "စကားပြောသည်" },
  { id: 193, "kanji": "話", "reading": "はなし", "meaning": "စကား၊ အကြောင်း" },
  { id: 194, "kanji": "電話", "reading": "でんわ", "meaning": "တယ်လီဖုန်း" },
  { id: 195, "kanji": "会話", "reading": "かいわ", "meaning": "စကားပြော" },
  { id: 196, "kanji": "読む", "reading": "よむ", "meaning": "ဖတ်သည်" },
  { id: 197, "kanji": "日本語", "reading": "にほんご", "meaning": "ဂျပန်ဘာသာ" },
  { id: 198, "kanji": "中国語", "reading": "ちゅうごくご", "meaning": "တရုတ်ဘာသာ" },
  { id: 199, "kanji": "外国語", "reading": "がいこくご", "meaning": "နိုင်ငံခြားဘာသာ" },
  { id: 200, "kanji": "間", "reading": "あいだ", "meaning": "ကြား" },
  { id: 201, "kanji": "時間", "reading": "じかん", "meaning": "အချိန်" },
  { id: 202, "kanji": "間に合う", "reading": "まにあう", "meaning": "အချိန်မီသည်" },
  { id: 203, "kanji": "聞く", "reading": "きく", "meaning": "နားထောင်သည်" },
  { id: 204, "kanji": "聞こえる", "reading": "きこえる", "meaning": "ကြားရသည်" },
  { id: 205, "kanji": "買う", "reading": "かう", "meaning": "ဝယ်သည်" },
  { id: 206, "kanji": "買い物", "reading": "かいもの", "meaning": "ဈေးဝယ်ခြင်း" },
  { id: 207, "kanji": "売買する", "reading": "ばいばいする", "meaning": "ရောင်းချသည်" },
  { id: 208, "kanji": "休み", "reading": "やすみ", "meaning": "ပိတ်ရက်၊ နားခြင်း" },
  { id: 209, "kanji": "休む", "reading": "やすむ", "meaning": "အနားယူသည်" },
  { id: 210, "kanji": "休日", "reading": "きゅうじつ", "meaning": "ပိတ်ရက်" },
  { id: 211, "kanji": "夏休み", "reading": "なつやすみ", "meaning": "နွေရာသီအားလပ်ရက်" },
  { id: 212, "kanji": "時", "reading": "とき", "meaning": "အချိန် (တုန်းက)" },
  { id: 213, "kanji": "時計", "reading": "とけい", "meaning": "နာရီ" },
  { id: 214, "kanji": "週", "reading": "しゅう", "meaning": "ရက်သတ္တပတ်" },
  { id: 215, "kanji": "今週", "reading": "こんしゅう", "meaning": "ဒီအပတ်" },
  { id: 216, "kanji": "道", "reading": "みち", "meaning": "လမ်း" },
  { id: 217, "kanji": "水道", "reading": "すいどう", "meaning": "ရေပိုက်" },
  { id: 218, "kanji": "今", "reading": "いま", "meaning": "အခု၊ ယခု" },
  { id: 219, "kanji": "今月", "reading": "こんげつ", "meaning": "ဒီလ၊ ယခုလ" },
  { id: 220, "kanji": "今日", "reading": "きょう", "meaning": "ဒီနေ့၊ ယနေ့" },
  { id: 221, "kanji": "今年", "reading": "ことし", "meaning": "ဒီနှစ်" },
  { id: 222, "kanji": "会う", "reading": "あう", "meaning": "တွေ့ဆုံသည်၊ တွေ့သည်" },
  { id: 223, "kanji": "会議", "reading": "かいぎ", "meaning": "အစည်းအဝေး" },
  { id: 224, "kanji": "会社", "reading": "かいしゃ", "meaning": "ကုမ္ပဏီ" },
  { id: 226, "kanji": "社会", "reading": "しゃかい", "meaning": "လူဘောင်လောက" },
  { id: 227, "kanji": "神社", "reading": "じんじゃ", "meaning": "နတ်ကွန်း" },
  { id: 228, "kanji": "店", "reading": "みせ", "meaning": "ဈေးဆိုင်" },
  { id: 229, "kanji": "店長", "reading": "てんちょう", "meaning": "ဆိုင်မန်နေဂျာ" },
  { id: 230, "kanji": "店員", "reading": "てんいん", "meaning": "ဆိုင်ဝန်ထမ်း" },
  { id: 231, "kanji": "駅", "reading": "えき", "meaning": "ဘူတာ" },
  { id: 232, "kanji": "駅前", "reading": "えきまえ", "meaning": "ဘူတာအရှေ့" },
  { id: 233, "kanji": "花", "reading": "はな", "meaning": "ပန်း" },
  { id: 234, "kanji": "花見", "reading": "はなみ", "meaning": "ပန်းကြည့်ခြင်း" },
  { id: 235, "kanji": "花火", "reading": "はなび", "meaning": "မီးပန်း" },
  { id: 236, "kanji": "花屋", "reading": "はなや", "meaning": "ပန်းဆိုင်" },
  { id: 237, "kanji": "国", "reading": "くに", "meaning": "တိုင်းပြည်" },
  { id: 238, "kanji": "白い", "reading": "しろい", "meaning": "ဖြူသော" },
  { id: 239, "kanji": "真っ白", "reading": "まっしろ", "meaning": "အဖြူဆွတ်ဆွတ်" },
  { id: 240, "kanji": "空", "reading": "そら", "meaning": "ကောင်းကင်" },
  { id: 241, "kanji": "大空", "reading": "おおぞら", "meaning": "ကောင်းကင်ကြီး" },
  { id: 242, "kanji": "空港", "reading": "くうこう", "meaning": "လေဆိပ်" },
  { id: 243, "kanji": "電気", "reading": "でんき", "meaning": "လျှပ်စစ်" },
  { id: 244, "kanji": "電池", "reading": "でんち", "meaning": "ဓာတ်ခဲ" }
];
